-- 2026-05-01 daily SQL delivery
-- Add schema changes and DBA-executed full-table SQL for this date in this file.

IF OBJECT_ID(N'[dbo].[tbl_doorman_blacklist]', N'U') IS NULL
BEGIN
CREATE TABLE [dbo].[tbl_doorman_blacklist] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [match_type] NVARCHAR(8) NOT NULL DEFAULT N'exact',
    [keyword] NVARCHAR(191) NOT NULL DEFAULT N'',
    [status] NVARCHAR(8) NOT NULL DEFAULT N'Enabled',
    [remark] NVARCHAR(255) NOT NULL DEFAULT N'',
    [last_ts] DATETIME2 NULL DEFAULT SYSUTCDATETIME(),
    [last_user] INT DEFAULT 0,
    [insert_ts] DATETIME2 NULL DEFAULT SYSUTCDATETIME(),
    [insert_user] INT DEFAULT 0,
    PRIMARY KEY ([id]),
    CONSTRAINT [UQ_tbl_doorman_blacklist_uniq_match_keyword] UNIQUE ([match_type],[keyword]),
    CONSTRAINT [CK_tbl_doorman_blacklist_match_type] CHECK ([match_type] IN (N'exact', N'contains')),
    CONSTRAINT [CK_tbl_doorman_blacklist_status] CHECK ([status] IN (N'Enabled', N'Disabled'))
);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'idx_status_match_type' AND object_id = OBJECT_ID(N'[dbo].[tbl_doorman_blacklist]'))
    CREATE INDEX [idx_status_match_type] ON [dbo].[tbl_doorman_blacklist] ([status],[match_type]);

MERGE [dbo].[tbl_doorman_blacklist] AS [target]
USING (VALUES
(N'exact', N'123456', N'Enabled', N'Common weak password'),
  (N'exact', N'1234567', N'Enabled', N'Common weak password'),
  (N'exact', N'12345678', N'Enabled', N'Common weak password'),
  (N'exact', N'123456789', N'Enabled', N'Common weak password'),
  (N'exact', N'1234567890', N'Enabled', N'Common weak password'),
  (N'exact', N'123123', N'Enabled', N'Common weak password'),
  (N'exact', N'123321', N'Enabled', N'Common weak password'),
  (N'exact', N'123qwe', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'123qweasd', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'1234qwer', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'654321', N'Enabled', N'Common weak password'),
  (N'exact', N'987654321', N'Enabled', N'Common weak password'),
  (N'exact', N'111111', N'Enabled', N'Common weak password'),
  (N'exact', N'11111111', N'Enabled', N'Common weak password'),
  (N'exact', N'222222', N'Enabled', N'Common weak password'),
  (N'exact', N'333333', N'Enabled', N'Common weak password'),
  (N'exact', N'444444', N'Enabled', N'Common weak password'),
  (N'exact', N'555555', N'Enabled', N'Common weak password'),
  (N'exact', N'666666', N'Enabled', N'Common weak password'),
  (N'exact', N'777777', N'Enabled', N'Common weak password'),
  (N'exact', N'888888', N'Enabled', N'Common weak password'),
  (N'exact', N'999999', N'Enabled', N'Common weak password'),
  (N'exact', N'000000', N'Enabled', N'Common weak password'),
  (N'exact', N'00000000', N'Enabled', N'Common weak password'),
  (N'exact', N'121212', N'Enabled', N'Common weak password'),
  (N'exact', N'112233', N'Enabled', N'Common weak password'),
  (N'exact', N'5201314', N'Enabled', N'Common weak password'),
  (N'exact', N'1314520', N'Enabled', N'Common weak password'),
  (N'exact', N'abc123', N'Enabled', N'Common weak password'),
  (N'exact', N'abc123456', N'Enabled', N'Common weak password'),
  (N'exact', N'abcd1234', N'Enabled', N'Common weak password'),
  (N'exact', N'qwerty', N'Enabled', N'Common weak password'),
  (N'exact', N'qwerty1', N'Enabled', N'Common weak password'),
  (N'exact', N'qwerty12', N'Enabled', N'Common weak password'),
  (N'exact', N'qwerty123', N'Enabled', N'Common weak password'),
  (N'exact', N'qwerty12345', N'Enabled', N'Common weak password'),
  (N'exact', N'qwertyuiop', N'Enabled', N'Common weak password'),
  (N'exact', N'asdfgh', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'asdf1234', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'asdfghjkl', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'zxcvbn', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'zxcvbnm', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'password', N'Enabled', N'Common weak password'),
  (N'exact', N'password1', N'Enabled', N'Common weak password'),
  (N'exact', N'password12', N'Enabled', N'Common weak password'),
  (N'exact', N'password123', N'Enabled', N'Common weak password'),
  (N'exact', N'password1234', N'Enabled', N'Common weak password'),
  (N'exact', N'password12345', N'Enabled', N'Common weak password'),
  (N'exact', N'password123456', N'Enabled', N'Common weak password'),
  (N'exact', N'passw0rd', N'Enabled', N'Common weak password'),
  (N'exact', N'p@ssword', N'Enabled', N'Common weak password'),
  (N'exact', N'p@ssw0rd', N'Enabled', N'Common weak password'),
  (N'exact', N'welcome', N'Enabled', N'Common weak password'),
  (N'exact', N'welcome1', N'Enabled', N'Common weak password'),
  (N'exact', N'welcome123', N'Enabled', N'Common weak password'),
  (N'exact', N'letmein', N'Enabled', N'Common weak password'),
  (N'exact', N'letmein123', N'Enabled', N'Common weak password'),
  (N'exact', N'iloveyou', N'Enabled', N'Common weak password'),
  (N'exact', N'1q2w3e4r', N'Enabled', N'Common weak password'),
  (N'exact', N'1qaz2wsx', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'1qazxsw2', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'zaq12wsx', N'Enabled', N'Common weak password'),
  (N'exact', N'zaq1zaq1', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'qazwsx', N'Enabled', N'Keyboard pattern'),
  (N'exact', N'admin', N'Enabled', N'Common weak password'),
  (N'exact', N'admin1', N'Enabled', N'Default credential'),
  (N'exact', N'admin12', N'Enabled', N'Default credential'),
  (N'exact', N'admin123', N'Enabled', N'Common weak password'),
  (N'exact', N'admin1234', N'Enabled', N'Default credential'),
  (N'exact', N'administrator', N'Enabled', N'Default credential'),
  (N'exact', N'root', N'Enabled', N'Default credential'),
  (N'exact', N'root123', N'Enabled', N'Default credential'),
  (N'exact', N'rootroot', N'Enabled', N'Default credential'),
  (N'exact', N'guest', N'Enabled', N'Default credential'),
  (N'exact', N'guest123', N'Enabled', N'Default credential'),
  (N'exact', N'test', N'Enabled', N'Default credential'),
  (N'exact', N'test123', N'Enabled', N'Default credential'),
  (N'exact', N'demo', N'Enabled', N'Default credential'),
  (N'exact', N'demo123', N'Enabled', N'Default credential'),
  (N'exact', N'login', N'Enabled', N'Default credential'),
  (N'exact', N'login123', N'Enabled', N'Default credential'),
  (N'exact', N'default', N'Enabled', N'Default credential'),
  (N'exact', N'changeme', N'Enabled', N'Default credential'),
  (N'exact', N'secret', N'Enabled', N'Common weak password'),
  (N'exact', N'secret123', N'Enabled', N'Common weak password'),
  (N'exact', N'master', N'Enabled', N'Common weak password'),
  (N'exact', N'master123', N'Enabled', N'Common weak password'),
  (N'exact', N'superuser', N'Enabled', N'Default credential'),
  (N'exact', N'service', N'Enabled', N'Default credential'),
  (N'exact', N'service123', N'Enabled', N'Default credential'),
  (N'exact', N'system', N'Enabled', N'Default credential'),
  (N'exact', N'system123', N'Enabled', N'Default credential'),
  (N'exact', N'manager', N'Enabled', N'Default credential'),
  (N'exact', N'manager123', N'Enabled', N'Default credential'),
  (N'exact', N'user', N'Enabled', N'Default credential'),
  (N'exact', N'user123', N'Enabled', N'Default credential'),
  (N'exact', N'user1234', N'Enabled', N'Default credential'),
  (N'exact', N'member', N'Enabled', N'Default credential'),
  (N'exact', N'member123', N'Enabled', N'Default credential'),
  (N'exact', N'staff', N'Enabled', N'Default credential'),
  (N'exact', N'staff123', N'Enabled', N'Default credential'),
  (N'exact', N'office', N'Enabled', N'Default credential'),
  (N'exact', N'office123', N'Enabled', N'Default credential'),
  (N'exact', N'company', N'Enabled', N'Default credential'),
  (N'exact', N'company123', N'Enabled', N'Default credential'),
  (N'exact', N'team', N'Enabled', N'Default credential'),
  (N'exact', N'team123', N'Enabled', N'Default credential'),
  (N'exact', N'hello', N'Enabled', N'Common weak password'),
  (N'exact', N'hello123', N'Enabled', N'Common weak password'),
  (N'exact', N'dragon', N'Enabled', N'Common weak password'),
  (N'exact', N'monkey', N'Enabled', N'Common weak password'),
  (N'exact', N'baseball', N'Enabled', N'Common weak password'),
  (N'exact', N'football', N'Enabled', N'Common weak password'),
  (N'exact', N'soccer', N'Enabled', N'Common weak password'),
  (N'exact', N'starwars', N'Enabled', N'Common weak password'),
  (N'exact', N'freedom', N'Enabled', N'Common weak password'),
  (N'exact', N'whatever', N'Enabled', N'Common weak password'),
  (N'exact', N'trustno1', N'Enabled', N'Common weak password'),
  (N'exact', N'princess', N'Enabled', N'Common weak password'),
  (N'exact', N'sunshine', N'Enabled', N'Common weak password'),
  (N'exact', N'lovely', N'Enabled', N'Common weak password'),
  (N'exact', N'flower', N'Enabled', N'Common weak password'),
  (N'exact', N'kitty', N'Enabled', N'Common weak password'),
  (N'exact', N'google', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'google123', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'apple', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'apple123', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'windows', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'windows123', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'android', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'android123', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'iphone', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'iphone123', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'samsung', N'Enabled', N'Brand-like weak password'),
  (N'exact', N'taiwan', N'Enabled', N'Locale weak password'),
  (N'exact', N'taipei', N'Enabled', N'Locale weak password'),
  (N'exact', N'happy', N'Enabled', N'Common weak password'),
  (N'exact', N'newyear2024', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'newyear2025', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'spring2024', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'spring2025', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'summer2024', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'summer2025', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'autumn2024', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'autumn2025', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'winter2024', N'Enabled', N'Seasonal weak password'),
  (N'exact', N'winter2025', N'Enabled', N'Seasonal weak password'),
  (N'contains', N'password', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'passw0rd', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'qwerty', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'asdf', N'Enabled', N'Contains keyboard pattern'),
  (N'contains', N'zxcv', N'Enabled', N'Contains keyboard pattern'),
  (N'contains', N'qazwsx', N'Enabled', N'Contains keyboard pattern'),
  (N'contains', N'123456', N'Enabled', N'Contains common number sequence'),
  (N'contains', N'654321', N'Enabled', N'Contains common number sequence'),
  (N'contains', N'111111', N'Enabled', N'Contains repeated number sequence'),
  (N'contains', N'000000', N'Enabled', N'Contains repeated number sequence'),
  (N'contains', N'abc123', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'admin', N'Enabled', N'Contains default credential keyword'),
  (N'contains', N'root', N'Enabled', N'Contains default credential keyword'),
  (N'contains', N'guest', N'Enabled', N'Contains default credential keyword'),
  (N'contains', N'test', N'Enabled', N'Contains default credential keyword'),
  (N'contains', N'demo', N'Enabled', N'Contains default credential keyword'),
  (N'contains', N'welcome', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'letmein', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'changeme', N'Enabled', N'Contains default credential keyword'),
  (N'contains', N'default', N'Enabled', N'Contains default credential keyword'),
  (N'contains', N'secret', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'service', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'system', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'manager', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'staff', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'member', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'office', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'company', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'team', N'Enabled', N'Contains common weak keyword'),
  (N'contains', N'newyear', N'Enabled', N'Contains seasonal keyword'),
  (N'contains', N'spring', N'Enabled', N'Contains seasonal keyword'),
  (N'contains', N'summer', N'Enabled', N'Contains seasonal keyword'),
  (N'contains', N'autumn', N'Enabled', N'Contains seasonal keyword'),
  (N'contains', N'winter', N'Enabled', N'Contains seasonal keyword')
) AS [source] ([match_type], [keyword], [status], [remark])
ON [target].[match_type] = [source].[match_type] AND [target].[keyword] = [source].[keyword]
WHEN MATCHED THEN
    UPDATE SET
        [status] = [source].[status],
        [remark] = [source].[remark],
        [last_ts] = SYSUTCDATETIME(),
        [last_user] = 0
WHEN NOT MATCHED THEN
    INSERT ([match_type], [keyword], [status], [remark])
    VALUES ([source].[match_type], [source].[keyword], [source].[status], [source].[remark]);
